version: "2"

services:
  web:
    build: .
    ports:
     - "8080:80"
    environment:
     - "APP_LOG=php://stderr"
     - "LOG_LEVEL=debug"
    volumes:
     - .:/var/www
    networks:
     - internal


networks:
  internal:
    driver: bridge
